# Generated by Django 4.0.2 on 2022-05-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('name', models.CharField(max_length=26, verbose_name='Name')),
                ('surname', models.CharField(max_length=26, verbose_name='Surname')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], verbose_name='Gender')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('balance_last_updated', models.FloatField(default=0, verbose_name='Balance last Updated')),
                ('balance_last_updated_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='Balance last Updated Time')),
                ('balance_for_withdraw', models.FloatField(default=0, verbose_name='Balance available for withdraw')),
                ('ref_balance_last_updated', models.FloatField(default=0, verbose_name='Referals balance last update')),
                ('ref_balance_last_updated_time', unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='Referal balance last updated time')),
                ('ref_code', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Referal code')),
                ('ref_amount_available', models.IntegerField(default=10)),
                ('ref_amount_filled', models.IntegerField(default=0)),
                ('ref_by', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Referred by')),
                ('apy', models.IntegerField(default=10)),
                ('usertype', models.CharField(choices=[('STANDARD', 'STANDARD'), ('MICROINF', 'MICROINF'), ('MACROINF', 'MACROINF')], default='STANDARD', max_length=20)),
                ('plan', models.CharField(choices=[('BASIC', 'BASIC'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD')], default='BASIC', max_length=10)),
                ('reset_password_token', models.UUIDField(default=None, verbose_name='Reset password token')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='UUID of user')),
                ('amount_kzt', models.FloatField(verbose_name='Amount of money in KZT')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('IN PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=25, verbose_name='Status')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time of withdraw')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='UUID of user')),
                ('amount_kzt', models.FloatField(verbose_name='Amount of money in KZT')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('IN PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=25, verbose_name='Status')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time of withdraw')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Wallet address')),
                ('mnemonic_key', models.TextField(verbose_name='Mnemonic key')),
                ('balance', models.FloatField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
