# Generated by Django 4.0.2 on 2022-03-17 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='UUID of user')),
                ('amount_kzt', models.FloatField(verbose_name='Amount of money in KZT')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('IN PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=25, verbose_name='Status')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time of withdraw')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='UUID of user')),
                ('amount_kzt', models.FloatField(verbose_name='Amount of money in KZT')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('IN PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=25, verbose_name='Status')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time of withdraw')),
            ],
        ),
    ]
