# Generated by Django 4.0.2 on 2022-05-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('MICROINF', 'MICROINF'), ('MACROINF', 'MACROINF'), ('TESTER', 'TESTER')], default='TESTER', max_length=20),
        ),
    ]
