# Generated by Django 4.0.2 on 2022-03-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Электронды пошта')),
                ('username', models.EmailField(max_length=60, unique=True, verbose_name='Электронды пошта')),
                ('name', models.CharField(default='', max_length=60, verbose_name='Аты-жөн')),
                ('surname', models.CharField(default='', max_length=60, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=60, null=True, verbose_name='Әкесінің аты')),
                ('role', models.CharField(max_length=255, verbose_name='Рөл')),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
