# Generated by Django 4.0.2 on 2022-03-22 15:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='apy',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_for_withdraw',
            field=models.FloatField(default=0, verbose_name='Balance available for withdraw'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_last_updated',
            field=models.FloatField(blank=True, null=True, verbose_name='Balance last Updated'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_last_updated_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Balance last Updated Time'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD')], default='BASIC', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_amount_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_amount_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_balance_last_updated',
            field=models.FloatField(default=0, verbose_name='Referals balance last update'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_balance_last_updated_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Referal balance last updated time'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_by',
            field=models.UUIDField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ref_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Referal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=26, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=26, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
