# Generated by Django 4.0.2 on 2022-03-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_patronymic_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ref_by',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
